#!/bin/bash
# Ensure all required packages are installed, including notebook
pip install notebook widgetsnbextension ipympl

# Enable widgets and ipympl extensions
jupyter nbextension enable --py widgetsnbextension --sys-prefix
jupyter nbextension enable --py ipympl --sys-prefix
