#!/bin/bash
# Install dependencies
pip install -r requirements.txt

# Enable widgets and ipympl extensions
jupyter nbextension enable --py widgetsnbextension --sys-prefix
jupyter nbextension enable --py ipympl --sys-prefix
