#!/bin/bash
# Install notebook and dependencies explicitly
pip install notebook==6.5.4 ipywidgets widgetsnbextension ipympl

# Reinstall nbextensions to ensure compatibility
pip install jupyter_contrib_nbextensions

# Enable nbextensions and ipympl extensions
jupyter contrib nbextension install --sys-prefix
jupyter nbextension enable --py widgetsnbextension --sys-prefix
jupyter nbextension enable --py ipympl --sys-prefix

